### ISSUE TITLE
Error: Cannot find module '../../lib/PriceMonitoring'

### ISSUE THREAD

**Issue by rafaelperozin** [roccomuso/price-monitoring#1]
When I run my code with little changes on example are returning:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../lib/PriceMonitoring'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\RMS\price-robot\competitors\RoofingSuperstore.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at C:\RMS\price-robot\node_modules\price-monitoring\lib\util.js:25:28
    at Array.forEach (<anonymous>)
    at autoload (C:\RMS\price-robot\node_modules\price-monitoring\lib\util.js:23:11)
    at new PriceMonitoring (C:\RMS\price-robot\node_modules\price-monitoring\lib\PriceMonitoring.js:19:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! price-robot@1.0.0 start: `node robot.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the price-robot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RafaelP\AppData\Roaming\npm-cache\_logs\2019-09-11T15_28_33_465Z-debug.log
```

**Comment by roccomuso** [comment]
what changes? please paste example
did you `npm install` ?

**Comment by rafaelperozin** [comment]
Sorry mate, reviewing what I changed to tell you I observed that I forgot to change `const SiteParser = require` on myParses files.

**Comment by roccomuso** [comment]
Don't worry ;)
